<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c742ea4c-2437-4607-8d54-e505672bb457}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    toggleOutput : BOOL := FALSE; // Output toggles every 5 seconds
    timer        : TON;           // Timer function block
    timerPeriod  : TIME := T#5S;  // Duration for high and low states
	
	FB2_Counters : FB2_Counters;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

FB2_Counters();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="64" Count="1" />
      <LineId Id="62" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>